COUNTRY_CODES = {
    "Brazil": "BR",
    "USA": "US",
    "Mexico": "MX",
    "Japan": "JP",
    "Australia": "AU",
    "Argentina": "AR",
    "Canada": "CA",
    "Malaysia": "MY",
    "United Kingdom": "GB",
    "Spain": "ES",
    "France": "FR",
    "Colombia": "CO",
    "India": "IN",
    "Philippines": "PH",
    "Germany": "DE",
    "Italy": "IT",
    "Portugal": "PT",
    "New Zealand": "NZ",
    "Taiwan": "TW",
    "Indonesia": "ID",
    "Ireland": "IE",
    "Thailand": "TH",
    "Turkey": "TR",
    "Dominican Republic": "DO",
    "Hong Kong": "HK",
    "Ecuador": "EC",
    "South Korea": "KR",
    "Netherlands": "NL",
    "Russia": "RU",
    "United Arab Emirates": "AE",
    "China": "CN",
    "Uruguay": "UY",
    "Czech Republic": "CZ",
    "Chile": "CL",
    "Singapore": "SG",
    "Peru": "PE",
    "Poland": "PL",
    "Greece": "GR",
    "Israel": "IL",
    "South Africa": "ZA",
    "Austria": "AT",
    "Egypt": "EG",
    "Norway": "NO",
    "Bulgaria": "BG",
    "Cuba": "CU",
    "Costa Rica": "CR",
    "Jamaica": "JM",
    "Vietnam": "VN",
    "Sweden": "SE",
    "Puerto Rico": "PR",
    "Switzerland": "CH",
    "Guatemala": "GT",
    "Luxembourg": "LU",
    "Panama": "PA",
    "Iceland": "IS",
    "Morocco": "MA",
    "French Antilles": "FR",
    "Fiji": "FJ",
    "Romania": "RO",
    "Bahamas": "BS",
    "Senegal": "SN",
    "Honduras": "HN",
    "Venezuela": "VE",
    "Belgium": "BE",
    "Bolivia": "BO",
    "Slovakia": "SK",
    "Saint Lucia": "LC",
    "Denmark": "DK",
    "Jordan": "JO",
    "Hungary": "HU",
    "Nicaragua": "NI",
    "Lebanon": "LB",
    "Vatican City": "VA",
    "Finland": "FI",
    "Tunisia": "TN",
    "Samoa": "WS",
    "Cyprus": "CY",
    "Maldives": "MV",
    "French Polynesia": "PF",
    "El Salvador": "SV",
}
