from recsys.transformers import (
    FeatureEngScala,
    LagNumericalFeaturesWithinGroup,
    PandasToNpArray,
    PandasToRecords,
    RankFeatures,
)
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

numerical_features_scala = [
    "item_id",
    "price",
    "rank",
    "item_impressions",
    "item_clicks",
    "item_ctr",
    "item_user_impressions",
    "item_user_clicks",
    "item_user_ctr",
    "avg_jaccard_to_previous_interactions",
    "avg_jaccard_to_previous_interactions_session",
    "change_of_sort_order_last_timestamp",
    "change_of_sort_order_count",
    "clickout_item_last_timestamp",
    "clickout_item_count",
    "filter_selection_last_timestamp",
    "filter_selection_count",
    "interaction_item_deals_last_timestamp",
    "interaction_item_deals_count",
    "interaction_item_image_last_timestamp",
    "interaction_item_image_count",
    "interaction_item_info_last_timestamp",
    "interaction_item_info_count",
    "search_for_destination_last_timestamp",
    "search_for_destination_count",
    "search_for_item_last_timestamp",
    "search_for_item_count",
    "search_for_poi_last_timestamp",
    "search_for_poi_count",
    "interaction_item_info_item_last_timestamp",
    "interaction_item_info_item_count",
    "interaction_item_info_last_ref_jaccard",
    "interaction_item_info_same_last_item",
    "clickout_item_item_last_timestamp",
    "clickout_item_item_count",
    "clickout_item_last_ref_jaccard",
    "clickout_item_same_last_item",
    "search_for_item_item_last_timestamp",
    "search_for_item_item_count",
    "search_for_item_last_ref_jaccard",
    "search_for_item_same_last_item",
    "interaction_item_image_item_last_timestamp",
    "interaction_item_image_item_count",
    "interaction_item_image_last_ref_jaccard",
    "interaction_item_image_same_last_item",
    "interaction_item_deals_item_last_timestamp",
    "interaction_item_deals_item_count",
    "interaction_item_deals_last_ref_jaccard",
    "interaction_item_deals_same_last_item",
]

numerical_features_for_ranking_scala = [
    "item_id",
    "price",
    "rank",
    "item_impressions",
    "item_clicks",
    "item_ctr",
    "item_user_impressions",
    "item_user_clicks",
    "item_user_ctr",
    "avg_jaccard_to_previous_interactions",
    "avg_jaccard_to_previous_interactions_session",
    "change_of_sort_order_last_timestamp",
    "change_of_sort_order_count",
    "clickout_item_last_timestamp",
    "clickout_item_count",
    "filter_selection_last_timestamp",
    "filter_selection_count",
    "interaction_item_deals_last_timestamp",
    "interaction_item_deals_count",
    "interaction_item_image_last_timestamp",
    "interaction_item_image_count",
    "interaction_item_info_last_timestamp",
    "interaction_item_info_count",
    "search_for_destination_last_timestamp",
    "search_for_destination_count",
    "search_for_item_last_timestamp",
    "search_for_item_count",
    "search_for_poi_last_timestamp",
    "search_for_poi_count",
    "interaction_item_info_item_last_timestamp",
    "interaction_item_info_item_count",
    "interaction_item_info_last_ref_jaccard",
    "interaction_item_info_same_last_item",
    "clickout_item_item_last_timestamp",
    "clickout_item_item_count",
    "clickout_item_last_ref_jaccard",
    "clickout_item_same_last_item",
    "search_for_item_item_last_timestamp",
    "search_for_item_item_count",
    "search_for_item_last_ref_jaccard",
    "search_for_item_same_last_item",
    "interaction_item_image_item_last_timestamp",
    "interaction_item_image_item_count",
    "interaction_item_image_last_ref_jaccard",
    "interaction_item_image_same_last_item",
    "interaction_item_deals_item_last_timestamp",
    "interaction_item_deals_item_count",
    "interaction_item_deals_last_ref_jaccard",
    "interaction_item_deals_same_last_item",
]
categorical_features_scala = [
    "session_id",
    "platform",
    "city",
    "device",
    "last_sort_order",
    "last_filter_selection",
    "country",
]


def make_vectorizer_1_scala(
    categorical_features=categorical_features_scala,
    numerical_features=numerical_features_scala,
    numerical_features_for_ranking=numerical_features_for_ranking_scala,
):
    return make_pipeline(
        FeatureEngScala(),
        ColumnTransformer(
            [
                (
                    "numerical",
                    make_pipeline(PandasToNpArray(), SimpleImputer(strategy="mean"), StandardScaler()),
                    numerical_features,
                ),
                ("numerical_context", LagNumericalFeaturesWithinGroup(), numerical_features + ["clickout_id"]),
                ("categorical", make_pipeline(PandasToRecords(), DictVectorizer()), categorical_features),
                ("numerical_ranking", RankFeatures(), numerical_features_for_ranking + ["clickout_id"]),
            ]
        ),
    )
